PUT /default/_mapping

{
  "properties": {
    "payload": {
      "properties": {
        "ingested": {
          "type": "date",
          "format": "date_time"
        },
        "fields": {
          "properties": {
            "date": {
              "type": "date",
              "format": "yyyy-MM-dd"
            }
          }
        }
      }
    }
  }
}
