streamx.blueprints.indexable-resources-sql-transformer.persisted-data.include-content=false
streamx.blueprints.indexable-resources-sql-transformer.persisted-data.fields=url,author,description,publication_date,modification_date
streamx.blueprints.indexable-resources-sql-transformer.persisted-data.facets=size,category
streamx.blueprints.indexable-resources-sql-transformer.transformations.latest-articles-rss.sql-query=SELECT * FROM indexable_resource
