streamx.blueprints.indexable-resources-producer.index-fragments=false

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.no-index.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.no-index.no-index=true
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.no-index.element-selector=//*[local-name()='meta'][@name='robots' and contains(concat(',', translate(@content, ' ', ''), ','), ',noindex,')]
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.no-index.key=robots
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.no-index.value=noindex

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.facet=true
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.element-selector=//*[local-name()='meta'][starts-with(@property, 'facets:')]
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-selector=./@property
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.value-selector=./@content
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors.trim.name=trim
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors.lowercase.name=lowercase
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors.removeStart.name=removeStart
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors.removeStart.config=facets:

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.value-processors.trim.name=trim

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.element-selector=//*[local-name()='meta'][@property='description']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.key=description
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.element-selector=//*[local-name()='meta'][@property='date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.key=date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.element-selector=//*[local-name()='meta'][@property='publication_date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.key=publication_date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.element-selector=//*[local-name()='meta'][@property='modification_date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.key=modification_date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.element-selector=//*[local-name()='meta'][@property='author']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.key=author
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.value-selector=./@content
