streamx.blueprints.indexable-resources-producer.index-fragments=false

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.facet=true
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.element-selector=//*[local-name()='meta'][starts-with(@property, 'facets:')]
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-selector=./@property
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.value-selector=./@content
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors[0].name=trim
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors[1].name=lowercase
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors[2].name=removeStart
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.key-processors[2].config=facets:
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.eds.value-processors[0].name=trim

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.element-selector=//*[local-name()='meta'][@property='description']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.key=description
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.field-description.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.element-selector=//*[local-name()='meta'][@property='date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.key=date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.element-selector=//*[local-name()='meta'][@property='publication_date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.key=publication_date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.publication-date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.element-selector=//*[local-name()='meta'][@property='modification_date']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.key=modification_date
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.modification-date.value-selector=./@content

streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.facet=false
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.element-selector=//*[local-name()='meta'][@property='author']
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.key=author
streamx.blueprints.indexable-resources-producer.search-feed-extractor.xpath.fields.author.value-selector=./@content
