global:
  services:
    processing:
      indexable-resources-sql-transformer:
        stateful: true
      rendering-engine:
        stateful: true
    edge:
      opensearch-sink:
        stateful: true
        replicas: 2
      web-server-sink:
        stateful: true
        replicas: 2
clusters:
  eu-west-par-processing:
    enabled: true
  eu-south-mil-edge:
    enabled: true
